server:
  port: 8081
spring:
 datasource:
  url: jdbc:mysql://localhost:3306/hotel
  username: root
  password: test
 jpa:
  hibernate:
   ddl-auto : update
   dialect: org.hibernate.dialect.MySQL8Dialect
   show-sql: true
   application:
    name: Hotel-SERVICE

eureka:
 instance:
  prefer-ip-address: true
 client:
  fetch-registry: true
  register-with-eureka: true
  service-url:
   defaultZone: http://localhost:8084/eureka




